### ISSUE TITLE
Clear Button

### ISSUE THREAD

**Issue by Umoren** [BolajiAyodeji/netty-finder#18]
_Hello Guys_
This project is really cool. 
I think we could remove the clear button and use the submit button for clearing the form inputs after submission.
There's a similar solution  [here](https://stackoverflow.com/questions/14589193/clearing-my-form-inputs-after-submission#_=_)
This is the first time i'm contributing to a project so bear with my novice inefficiencies.

**Comment by BolajiAyodeji** [comment]
Awesome!
Send a PR fix, we would merge.
@Umoren 
I hope you know this is not a contact form?
The page does not load after submission.
The script only runs and displays your result immediately.
So whatever fix you send, try to keep that in mind.

Nice issue! :+1:

**Comment by fakela** [comment]
@BolajiAyodeji the clear button i really dont see its need...using a phone or laptop is easy to clear errors with just the keyboard

**Comment by BolajiAyodeji** [comment]
@fakela The idea of the clear button is not only to clear errors.
Once you try for a number, the user would want to test another number, this is what the clear button does, clears the input field for another netty-finder.
We're trying to build an inclusive app where even the lazy have a say! :smile:

**Comment by BolajiAyodeji** [comment]
@fakela you could send a PR tho

**Comment by BolajiAyodeji** [comment]
@Umoren I totally understand how you feel.
Please don't give up.
You're not terrible, programming Is.
I'm leaving this issue open, Keep trying!

**Comment by Umoren** [comment]
OK I tried something different but you might not like it.
The submit button **RESETS** the page.
They are two positives from this
1. The input fields would be cleared when the user initiates another netty-finder.
2. The browsers now activates [autocomplete = "on"] on the textboxes which is really cool i think.
They are also two negatives
1. The page refreshes really fast so the user doesn't have much time to see the result. (I think i can fix this but i'm not sure)

This is actually the first time i didn't destroy much.
  `  <input type="submit"  class="form-control"  onclick="compute(form); this.form.reset()" >Submit</button>`
So what do you think?

**Comment by BolajiAyodeji** [comment]
@Umoren This issue has been fixed by #23 
Thank you for raising it, credits to you :+1:

**Comment by BolajiAyodeji** [comment]
@all-contributors please add @Umoren for code

**Comment by BolajiAyodeji** [comment]
@all-contributors please add @fakela for ideas
