### ISSUE TITLE
Make error notifications display below the form

### ISSUE THREAD

**Issue by BolajiAyodeji** [BolajiAyodeji/netty-finder#19]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AsaoluElijah** [comment]
You mean if the number is invalid, it should show an error?
I can work on that.

**Comment by BolajiAyodeji** [comment]
Right now all errors display in form of an alert prompt.
All errors should be displayed within the app with a specific style guide.

**Comment by AsaoluElijah** [comment]
Ok, I'll work on it.

**Comment by BolajiAyodeji** [comment]
Alright, Great!

**Comment by AsaoluElijah** [comment]
I just created a pull request. I  hope its merged soon.
And also I couldnt find the line where the success response is display,
I mean the line with the code alert(iInput + " belongs to "network);

**Comment by BolajiAyodeji** [comment]
Fixed!
