### ISSUE TITLE
Add new features

### ISSUE THREAD

**Issue by BolajiAyodeji** [BolajiAyodeji/netty-finder#20]

**Comment by bytenaija** [comment]
I could do the api in express

**Comment by BolajiAyodeji** [comment]
Thank you @bytenaija 
Please go Ahead.

**Comment by BolajiAyodeji** [comment]
You can drop features you have in mind to be added also

**Comment by BolajiAyodeji** [comment]
Check #27 for the API issue

**Comment by BolajiAyodeji** [comment]
Hello, @bytenaija still working on the api?
