### ISSUE TITLE
Add NODEJS Screenshot

### ISSUE THREAD

**Issue by BolajiAyodeji** [BolajiAyodeji/netty-finder#26]
@CITGuru can you add a little screenshot of the npm version?

**Comment by CITGuru** [comment]
![screenshot from 2018-11-13 10-48-49](https://user-images.githubusercontent.com/16475846/48405025-c63b7800-e731-11e8-80ed-b64e72f0c526.png)
Can you do it instead, my hands are tight right now. Here's a screenshot

**Comment by BolajiAyodeji** [comment]
Alright @CITGuru 
Thank you!

**Comment by CITGuru** [comment]
Any plan for a rest api, i think it would be nice if you have one. The rest api can be base on Django or Express. This will be easier since we already nodejs and python version

**Comment by CITGuru** [comment]
Lets see, not sure tho. But the rest api will probably be base on python/django cos of time

**Comment by CITGuru** [comment]
@BolajiAyodeji Another thing is try and redesign the website. So many redundant element and color combo. Design something minimal, with the three colors. I know its not easy just try to. And also on the website show other versions and packages. Look at this https://indreed.herokuapp.com/

**Comment by BolajiAyodeji** [comment]
What part contains Redundant elements?

Kindly raise another issue for the UI Redesign so we can look into it.

Would check that link and add all other packages to the site.

**Comment by BolajiAyodeji** [comment]
I just checked the link, nice.

In summary what would our API do?

**Comment by CITGuru** [comment]
Returns the phone, network, valid, phone_prefix
```json
{
    "phone":"08182315466",
    "network:"9mobile",
    "prefix":"0812",
   "valid": true
}
```

**Comment by BolajiAyodeji** [comment]
Cool @CITGuru 
You can proceed!

We'd add more features soon!
I still have few features in view.

**Comment by CITGuru** [comment]
And also we should try making it detect all kinds of phone number network. Thats a future feature tho

**Comment by BolajiAyodeji** [comment]
Raise the issue for UI Redesign!
