### ISSUE TITLE
Build NettyFinder API

### ISSUE THREAD

**Issue by BolajiAyodeji** [BolajiAyodeji/netty-finder#27]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
An API for the NettyFinder project
Should return `phone number` `prefix` `number validity` and `network provider`

**Describe alternatives you've considered**
Node JS

**Additional context**

**Comment by BolajiAyodeji** [comment]
@bytenaija @CITGuru

**Comment by CITGuru** [comment]
http://nettyfinder.herokuapp.com/ Thats the api endpoints I created on heroku. Haven't had extra time to push it. Its just basic django json response. No rest api framework. I'll also enable CORS for ajax and fetch support. @BolajiAyodeji

**Comment by CITGuru** [comment]
??

**Comment by BolajiAyodeji** [comment]
Sorry for the delay @CITGuru 
Can you please provide a quick documentation of this API so we make it public?

**Comment by BolajiAyodeji** [comment]
@CITGuru Still open?
Kindly re-visit this issue thread.

**Comment by sayoadesokan** [comment]
Was the api for this, still done? or I can create an issue and create api for this with it's documentation @BolajiAyodeji

**Comment by BolajiAyodeji** [comment]
> Was the api for this, still done? or I can create an issue and create api for this with it's documentation @BolajiAyodeji

Hi @sayoadesokan! Thanks for indicating interest.

I'm working on revamping the entire project, and the API will come with that. Once that is live, I'd be open to further contributions and improvements. Thank you!

**Comment by BolajiAyodeji** [comment]
I'll close this issue now, too, since it's not needed anymore. Thank you.
