### ISSUE TITLE
Detect Numbers that have migrated to another network

### ISSUE THREAD

**Issue by tobiamos** [BolajiAyodeji/netty-finder#41]
We are unable to know if a number is migrated or not
**Describe the solution you'd like**
Given a Nigerian phone number
When a migrated number is added to the input field
Then we should be able to know its original network and the network it migrated to

**Comment by BolajiAyodeji** [comment]
Hello there,
Thank you for opening this issue, I never thought of this and haven't experienced number migration before.

Do you have any idea how migration works for Nigerian numbers, some more information would be great to help facilitate this feature?
Cheers!

**Comment by stanleyume** [comment]
Hi @BolajiAyodeji 

[https://www.mtnonline.com/personal/port/](https://www.mtnonline.com/personal/port/)

You can "port" to another network while retaining your original number.

**Comment by antonellopasella** [comment]
There is no way to know this info, in my experience

**Comment by BolajiAyodeji** [comment]
> There is no way to know this info, in my experience

I agree @antonellopasella, the best we can do here is to add a disclaimer for migrated numbers.

What are your thoughts?
