### ISSUE TITLE
Unable to see network name when I search

### ISSUE THREAD

**Issue by narthkings** [BolajiAyodeji/netty-finder#43]
After typing in my number and searching, it doesn’t show the network I use

![42E115DD-30E8-402E-99A4-E83EB374BD03](https://user-images.githubusercontent.com/25045543/68086173-2ea2ce00-fe49-11e9-8ff6-afa36254240e.png)

**Comment by BolajiAyodeji** [comment]
@all-contributors please add @narthkings for bug
