### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by codiini** [BolajiAyodeji/netty-finder#56]
Just wanted to point out that the site is down:

<img width="768" alt="image" src="https://github.com/user-attachments/assets/c34b9ebf-05c4-4b48-9157-530c493952d5">

**Comment by BolajiAyodeji** [comment]
Thanks for reporting this, @codiini!

Apparently, Netlify doesn't support using the [netlify.com](http://netlify.com/) domain anymore but instead [netlify.app](http://netlify.app/). I've updated the repo link to https://netty-finder.netlify.app now.

I should get in some updates on the entire project soon too; thank you.
